version: "3.9"
services:

  registry:
    container_name: registry
    image: registry:2.8.2
    restart: unless-stopped
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_AUTH_TOKEN_SERVICE: myregistry
      REGISTRY_AUTH_TOKEN_REALM: http://localhost:8080/realms/myrealm/protocol/docker-v2/auth
      REGISTRY_AUTH_TOKEN_ISSUER: http://localhost:8080/realms/myrealm
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /opt/certs/localhost_trust_chain.pem
    volumes:
      - certs:/opt/certs/:ro # certs from registry client export in keycloak
    networks:
      - registry

  database:
    container_name: database
    image: mariadb:10.9.5
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: database
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    networks:
      - database

  keycloak:
    container_name: keycloak
    build:
      context: ../../
      dockerfile: examples/keycloak-with-mapper/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      REGISTRY_CATALOG_AUDIENCE: editor #user|editor
      REGISTRY_NAMESPACE_SCOPE: group #username|group|group,username
      KC_LOG_LEVEL: info #info|debug|trace|warn
      KC_DB_URL: jdbc:mariadb://database:3306/database
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: "8080"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
    depends_on:
        - database
    networks:
      - database
      - registry

networks:
  database:
  registry:
